allowedOrigins:
  # - https://dev-admin.example.com
  - http://localhost:5173

vpc:
  subnetIds:
    - subnet-060d04de6760954b0
    - subnet-04faae770c7f5cb4a
    - subnet-0a9acd69d0477c50f
  securityGroupIds:
    - sg-07b46cc5df8cba3db

database:
  host: itcenter-auth.cfeacycaqhdx.ap-southeast-2.rds.amazonaws.com
  port: 5432
  user: postgres
  password: password
  name: itcenter-auth
  ssl: true
  poolMax: 10

cognito:
  region: ap-southeast-2
  userPoolId: ap-southeast-2_hTAYJId8y
  clientId: 3rdnl5ind8guti89jrbob85r4i

graph:
  tenant: dev-tenant-id
  clientId: dev-graph-client-id
  clientSecret: dev-graph-client-secret
  scope: https://graph.microsoft.com/.default

featureFlags:
  geoValidationEnabled: false
  calendarSyncEnabled: true

calendarSync:
  visibilityTimeout: 60
  maxReceiveCount: 3

provisionedConcurrency:
  clockIn: 0
  clockOut: 0

