allowedOrigins:
  - https://stg-admin.example.com
  - https://stg-flutter.example.com

vpc:
  subnetIds:
    - subnet-aaaaaaaa
    - subnet-bbbbbbbb
  securityGroupIds:
    - sg-cccccccc

dbSecretArn: arn:aws:secretsmanager:ap-southeast-2:123456789012:secret:itcenter/stg/db
dbProxyEndpoint: itcenter-stg-proxy.proxy-qrstuvwxyzabcdef.ap-southeast-2.rds.amazonaws.com
dbPoolMax: 10

cognito:
  region: ap-southeast-2
  userPoolId: ap-southeast-2_stgPool
  clientId: stgClientIdPlaceholder

graph:
  tenant: stg-tenant-id
  clientId: stg-graph-client-id
  clientSecret: stg-graph-client-secret
  scope: https://graph.microsoft.com/.default

featureFlags:
  geoValidationEnabled: false
  calendarSyncEnabled: true

calendarSync:
  visibilityTimeout: 60
  maxReceiveCount: 3

provisionedConcurrency:
  clockIn: 1
  clockOut: 1

